apiVersion: v1
kind: ConfigMap
metadata:
  name: web-content
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title> slay besty!</title>
    </head>
    <body>
        <h1> HIIIIII! </h1>
        <p> This is a test to see if you can slay as my kween. GOOD SHIT! </p>
    </body>
