apiVersion: apps/v1
kind: Deployment

metadata:
  name: eureka
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: eureka
  template:
    metadata:
      labels:
        app.kubernetes.io/name: eureka
    spec:
      containers:
        - name: eureka
          image: eureka:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8761
              name: eureka-port